// components/LeftTreeGLB.tsx
//
// The left-gutter tree trunk. Procedurally generated by
// blender/build_left_tree_blender.py, which derives every dimension from
// public/fauna/left_tree.png so the model drops into the exact footprint the
// PNG used to occupy.
//
// Geometry facts this component relies on:
//   * 9.20 world units tall, base sitting on y = 0
//   * trunk centreline at x ~= 0 (it sways +/-0.075, the root flare reaches ~0.6)
//   * baked vertex colours (COLOR_0), no textures, so nothing else to load
//   * smooth normals — the faceted look of the old PNG is gone on purpose
//
// No branches yet. When they land they come from the same GLB, so nothing here
// needs to change.
"use client";

import { useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

const MODEL = "/models/left_tree.glb";

export default function LeftTreeGLB() {
  const gltf = useGLTF(MODEL) as unknown as { scene: THREE.Group };

  // useGLTF caches and shares the scene and its materials across every consumer
  // of the same URL. Clone both so a second mount (or a hot reload) can't hand
  // two mounts the same objects.
  const tree = useMemo(() => {
    const root = gltf.scene.clone(true);

    root.traverse((obj) => {
      const mesh = obj as THREE.Mesh;
      if (!mesh.isMesh) return;

      const src = mesh.material as THREE.MeshStandardMaterial;
      const mat = src.clone();

      // GLTFLoader already sets this from the COLOR_0 attribute; being explicit
      // means a re-export that drops vertex colours fails loudly (white trunk)
      // rather than quietly falling back to the material colour.
      mat.vertexColors = true;
      mat.metalness = 0;
      mat.roughness = 0.95;

      // Exported doubleSided because Blender defaults to it. The trunk is a
      // closed solid, so back faces are never visible — front-only halves the
      // fragment work and stops interior faces from catching light at the
      // grazing angles you get near the top of the strip.
      mat.side = THREE.FrontSide;

      mesh.material = mat;
      mesh.castShadow = true;
      mesh.receiveShadow = true;
    });

    return root;
  }, [gltf.scene]);

  return <primitive object={tree} />;
}

useGLTF.preload(MODEL);
